// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopsRUs.API.Data;

namespace ShopsRUs.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220422073427_InitialContext")]
    partial class InitialContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ShopsRUs.API.Models.Entities.Discounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRatePercentage")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRatePercentage = true,
                            Name = "Employee Discount",
                            Rate = 30m,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRatePercentage = true,
                            Name = "Affiliate Discount",
                            Rate = 10m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRatePercentage = true,
                            Name = "Loyal Customer Discount",
                            Rate = 5m,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRatePercentage = false,
                            Name = "Price Discount",
                            Rate = 5m,
                            Type = 4
                        });
                });

            modelBuilder.Entity("ShopsRUs.API.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("OrderId")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 82, DateTimeKind.Local).AddTicks(6838),
                            InvoiceNumber = "A001",
                            OrderId = 1,
                            OrderTotal = 0m,
                            Total = 500m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 82, DateTimeKind.Local).AddTicks(6996),
                            InvoiceNumber = "A002",
                            OrderId = 2,
                            OrderTotal = 0m,
                            Total = 1500m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 82, DateTimeKind.Local).AddTicks(7002),
                            InvoiceNumber = "A003",
                            OrderId = 3,
                            OrderTotal = 0m,
                            Total = 990m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 82, DateTimeKind.Local).AddTicks(7005),
                            InvoiceNumber = "A004",
                            OrderId = 4,
                            OrderTotal = 0m,
                            Total = 920m,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ShopsRUs.API.Models.Entities.InvoiceDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DerivedProductCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ProductPrice")
                        .HasMaxLength(30)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDerivedCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6304),
                            DerivedProductCost = 40m,
                            DiscountPrice = 2m,
                            InvoiceId = 1,
                            ProductId = 2,
                            ProductName = "Invoice Item 2",
                            ProductPrice = 20m,
                            ProductQuantity = 2,
                            TotalDerivedCost = 38m
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6504),
                            DerivedProductCost = 482m,
                            DiscountPrice = 20m,
                            InvoiceId = 1,
                            ProductId = 4,
                            ProductName = "Invoice Item 4",
                            ProductPrice = 482m,
                            ProductQuantity = 1,
                            TotalDerivedCost = 462m
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6514),
                            DerivedProductCost = 250m,
                            DiscountPrice = 0m,
                            InvoiceId = 2,
                            ProductId = 40,
                            ProductName = "Invoice Item 40",
                            ProductPrice = 50m,
                            ProductQuantity = 5,
                            TotalDerivedCost = 250m
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6517),
                            DerivedProductCost = 250m,
                            DiscountPrice = 25m,
                            InvoiceId = 3,
                            ProductId = 3,
                            ProductName = "Invoice Item 3",
                            ProductPrice = 50m,
                            ProductQuantity = 5,
                            TotalDerivedCost = 225m
                        },
                        new
                        {
                            Id = 5,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6521),
                            DerivedProductCost = 400m,
                            DiscountPrice = 20m,
                            InvoiceId = 3,
                            ProductId = 5,
                            ProductName = "Invoice Item 5",
                            ProductPrice = 400m,
                            ProductQuantity = 1,
                            TotalDerivedCost = 380m
                        },
                        new
                        {
                            Id = 6,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6526),
                            DerivedProductCost = 385m,
                            DiscountPrice = 0m,
                            InvoiceId = 3,
                            ProductId = 15,
                            ProductName = "Invoice Item 15",
                            ProductPrice = 77m,
                            ProductQuantity = 5,
                            TotalDerivedCost = 385m
                        },
                        new
                        {
                            Id = 7,
                            CreatedOnDate = new DateTime(2022, 4, 22, 10, 34, 27, 83, DateTimeKind.Local).AddTicks(6529),
                            DerivedProductCost = 1000m,
                            DiscountPrice = 80m,
                            InvoiceId = 4,
                            ProductId = 105,
                            ProductName = "Invoice Item 105",
                            ProductPrice = 200m,
                            ProductQuantity = 5,
                            TotalDerivedCost = 920m
                        });
                });

            modelBuilder.Entity("ShopsRUs.API.Models.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnDate = new DateTime(2019, 4, 22, 10, 34, 27, 79, DateTimeKind.Local).AddTicks(7635),
                            Email = "iismailakti@gmail.com",
                            FirstName = "İsmail",
                            LastName = "AKTI",
                            PhoneNumber = "123456789",
                            UserType = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnDate = new DateTime(2022, 1, 22, 10, 34, 27, 81, DateTimeKind.Local).AddTicks(6867),
                            Email = "user2@email.com",
                            FirstName = "Mehmet",
                            LastName = "KAPLAN",
                            PhoneNumber = "12345678910",
                            UserType = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnDate = new DateTime(2021, 4, 22, 10, 34, 27, 81, DateTimeKind.Local).AddTicks(6973),
                            Email = "user3@email.com",
                            FirstName = "Penny",
                            LastName = "Jackson",
                            PhoneNumber = "123456789",
                            UserType = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnDate = new DateTime(2017, 4, 22, 10, 34, 27, 81, DateTimeKind.Local).AddTicks(6981),
                            Email = "user4@email.com",
                            FirstName = "Amy",
                            LastName = "Fowler",
                            PhoneNumber = "123456789",
                            UserType = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedOnDate = new DateTime(2019, 4, 22, 10, 34, 27, 81, DateTimeKind.Local).AddTicks(6984),
                            Email = "user5@email.com",
                            FirstName = "Raj",
                            LastName = "Koothrappali",
                            PhoneNumber = "123456789",
                            UserType = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
